# encoding: UTF-8

require 'rake'
require 'rspec/core/rake_task'

driver = ENV['DRIVER'] || 'vagrant'

unless driver.eql?('vagrant') || driver.eql?('docker')
  puts "Set the DRIVER environment variable either to 'vagrant' or 'docker'"
  exit 1
end

task spec: 'spec:all'

namespace :spec do
  desc 'Run serverspec'
  RSpec::Core::RakeTask.new(:all) do |t|
    ENV['DRIVER'] = driver
    t.pattern = "spec/base,spec/#{driver}/*_spec.rb"
    t.rspec_opts = "--tag ~#{driver}:false"
  end
end
