api:
  build: api/
  links:
    - mongo
  environment:
    - MONGO_URL=mongo
  container_name: dillojs-api

mongo:
  image: mongo
  container_name: dillojs-mongo

nginx:
  image: nginx
  ports:
    - "80:80"
  links:
    - api
  volumes:
    - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
  volumes_from:
    - web
  container_name: dillojs-nginx

web:
  build: web/
  container_name: dillojs-web
